version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    container_name: social-multiplication-rabbitmq
    volumes:
      - ./../rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

#  jetty-server:
#    container_name: social-multiplication-jetty
#    image: jetty:9.4-jre11
#    volumes:
#      - ./ui/webapps:/var/lib/jetty/webapps/ui
#      - ./ui/start.d:/var/lib/jetty/start.d
#    ports:
#      - 9090:9090
#      - 443:8443