server:
  port: 8000

zuul:
  prefix: /api
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    multiplications:
      path: /multiplications/**
      url: http://localhost:8080/multiplications
    results:
      path: /results/**
      url: http://localhost:8080/results
    leaders:
      path: /leaders/**
      url: http://localhost:8081/leaders
    stats:
      path: /stats/**
      url: http://localhost:8081/stats

endpoints:
  trace:
    sensitive: false

ribbon:
  eureka:
    enabled: false
